name: pypc
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - plotly
  - neptune
  - tqdm
  - pytorch
  # - pytorch-cuda=12.1
  - torchaudio
  - torchvision